"""
api_server.py — WxCC SLM Phase 3: FastAPI REST Endpoint
========================================================
Exposes the SLM pipeline as a REST API consumed by the
abhavtech.com website and the Streamlit demo app.

Save to: D:/project-slm-webex\api_server.py

Dependencies:
    pip install fastapi uvicorn python-dotenv

Run:
    From D:/project-slm-webex>, run:
    uvicorn api_server:app --host 0.0.0.0 --port 8000 --reload
"""

import os
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
from dotenv import load_dotenv

load_dotenv()  # loads D:/project-slm-webex\.env

from slm_pipeline import run, SLMResponse

app = FastAPI(
    title="AbhavTech WxCC SLM",
    description="Domain-specific AI consulting for Cisco Webex Contact Center",
    version="1.0.0",
)

# CORS — allow the Streamlit demo and abhavtech.com
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://abhavtech.com",
        "https://www.abhavtech.com",
        "http://localhost:8501",   # Streamlit local dev
        "http://localhost:3000",
    ],
    allow_methods=["POST", "GET"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------

class QueryRequest(BaseModel):
    query:    str
    history:  Optional[list[dict]] = None   # [{"role": "user"|"assistant", "content": "..."}]
    top_k:    Optional[int] = 8


class SourceRef(BaseModel):
    filename:        str
    doc_id:          str
    provenance_tier: int
    source_url:      str
    score:           float


class QueryResponse(BaseModel):
    answer:               str
    intent:               str
    domain:               str
    compliance_flags:     list[str]
    stop_condition:       Optional[str]
    clarification_needed: bool
    clarification_question: Optional[str]
    sources:              list[SourceRef]
    latency_ms:           int
    tokens_used:          dict
    knowledge_date:       str
    # EU Art 50 AI disclosure (required from 2 Aug 2026)
    ai_disclosure:        str = (
        "This response was generated by an AI system (AbhavTech WxCC SLM). "
        "It is provided for informational purposes and should be verified "
        "against current Cisco documentation before implementation."
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/health")
def health():
    return {"status": "ok", "model": "AbhavTech WxCC SLM v1.0"}


@app.post("/query", response_model=QueryResponse)
def query(req: QueryRequest):
    if not req.query or not req.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")
    if len(req.query) > 4000:
        raise HTTPException(status_code=400, detail="Query exceeds 4000 character limit.")

    try:
        result: SLMResponse = run(
            query=req.query.strip(),
            conversation_history=req.history,
            top_k=req.top_k or 8,
        )
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        import traceback
        tb = traceback.format_exc()
        raise HTTPException(status_code=500, detail=f"Pipeline error: {e}\n{tb}")

    return QueryResponse(
        answer               = result.answer,
        intent               = result.intent,
        domain               = result.domain,
        compliance_flags     = result.compliance_flags,
        stop_condition       = result.stop_condition,
        clarification_needed = result.clarification_needed,
        clarification_question = result.clarification_question,
        sources              = [SourceRef(**s) for s in result.sources],
        latency_ms           = result.latency_ms,
        tokens_used          = result.tokens_used,
        knowledge_date       = result.knowledge_date,
    )


# ---------------------------------------------------------------------------
# .env template (printed if vars missing)
# ---------------------------------------------------------------------------

@app.on_event("startup")
def check_env():
    missing = [v for v in ["GROQ_API_KEY", "QDRANT_URL", "QDRANT_KEY"] if not os.environ.get(v)]
    if missing:
        print(f"\n!! Missing env vars: {missing}")
        print("   Create D:\\project-slm-webex\\.env with:")
        for v in missing:
            print(f"   {v}=your_value_here")
        print()
